spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager-db
    username: user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  url: http://localhost:8080/api
